### ISSUE TITLE
Discussion: Ideas

### ISSUE THREAD

**Issue by A** [rambler-digital-solutions/dotfiles#1]
Any yay or nay are welcomed! Just comment the issue below

**Comment by maxkoshel** [comment]
### Eslint

За основу взят конфиг от Airbnb.

Предлагаю убрать настройки:
"no-var": 2
"prefer-const": 2
"strict": [2, "never"]
"comma-dangle": [2, "always-multiline"]     // проблемы в IE8

И изменить значения:
"func-names": 0   // имена для анонимных функций
"no-use-before-define": [2, "nofunc"]   // исключение для функций

**Comment by dvetlugin** [comment]
со всем согласен

**Comment by Aminoser** [comment]
"curly": [2, "multi-line"] // спорно
"one-var": [2, "never"] // предлагаю убрать

**Comment by maxkoshel** [comment]
@Aminoser, по поводу "curly" я бы оставил как есть, чтобы была общая стилистика, а иначе кто как попало будет делать. "one-var" - когда каждая переменная на отдельной строке объявлена - такой код легче дебажить.

**Comment by Aminoser** [comment]
@maxkoshel "curly" - я за "all", т.к. считаю что записи вида:

``` javascript
if (foo) return; else doSomething();
```

или

``` javascript
if (foo) return;
else if (bar) baz()
else doSomething();
```

хуже читаемы чем:

``` javascript
if (foo) {
    return;
}

while (bar) {
    baz();
}

if (foo) {
    baz();
} else {
    qux();
}
```

Инлайн считаю нужно использовать в примерно таких ситуациях:

``` javascript
var a = b > 0 ? 1 : 100;
```

"one-var" - да, такой код легче дебажить, однако это единственный плюс, т.к. мне например запись вида:

``` javascript
var a = 1,
    b = 2,
    c = 3;
```

Более удобен для написания и чтения. Мне кажется в этом случае команда должна сама решать, т.к. не критический момент.

**Comment by ozio** [comment]
Плохо писать:

```
if (debug)
  return;
```

Хорошо:

```
if (debug) return;
```

в таком случае это будет проще и читаемее записи вида

```
if (debug) {
  return
}
```

, а запись

```
var a = 1,
    b = 2,
    c = 3;
```

ведёт к тому, что копипастнув код можно внезапно получить

```
var a = 1,
    b = 2;
    c = 3;
```

Гайдлайны AirBnb так же не рекомендуют такую запись.

**Comment by lgordey** [comment]
Если ориентироваться на airbnb, то все эти случаи там описаны.

@Aminoser например, к вопросу скобок https://github.com/airbnb/javascript/tree/master/es5#blocks

**Comment by Aminoser** [comment]
@lgordey если писать как 'good' - всеми руками за (скобки, остальное надо дочитать).

**Comment by mrsum** [comment]
@inthemon Ошибки бы в readme поправить еще. 
Instalation > Installation

> ssh on prodactions blocked by admins 

эта строчка не надо наверное

**Comment by dvetlugin** [comment]
изменил 
"indent": [2, 2]
на 
"indent": [2, 2, {"SwitchCase": 1}]

**Comment by dvetlugin** [comment]
@mrsum  
- ошибку исправил
- комментарий думаю лучше оставить, забудем потом.

**Comment by Aminoser** [comment]
@inthemon prod**A**ctions ?)

**Comment by maxkoshel** [comment]
предлагаю убрать правило "no-new", порой необходимо создавать экзепляры с помощью конструкторов, методы которых не вызываются и сами экзепляры никуда не передаются и используют уже существующий DOM.

**Comment by LendsMan** [comment]
Может обновимся?

> The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.
> The react/wrap-multilines rule is deprecated. Please use the react/jsx-wrap-multilines rule instead.

**Comment by mrsum** [comment]
И еще правило 

```
"react/jsx-sort-props": 1,
```

жутко тупое, неужели я должен по алфавитному порядку вписывать пропсы в реакт компонент >_<

**Comment by LendsMan** [comment]
Кто-нибудь знает тонкую грань между "import/newline-after-import" внутри require.ensure и "no-trailing-spaces"? *trollface*
